version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: srm-academia-bot
    restart: always
    expose:
      - "9000"   
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9000"]
      interval: 30s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: srm-academia-nginx
    restart: always
    ports:
      - "80:80"   
      - "443:443"   
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - telegram-bot