module.exports = {
  API_BASE_URL: process.env.API_BASE_URL,
  TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
  GROQ_API_KEY: process.env.GROQ_API_KEY,
  LOST_ITEM_API_URL: process.env.LOST_ITEM_API_URL,
  VAULTIFY_API_URL: process.env.VAULTIFY_API_URL,
  SEAT_FINDER_API_URL: process.env.SEAT_FINDER_API_URL,
  STUDENT_PORTAL_API_URL: process.env.STUDENT_PORTAL_API_URL,
};
