module.exports = {
  API_BASE_URL: process.env.API_BASE_URL,
  TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
  NOTIFICATION_API_URL: process.env.NOTIFICATION_API_URL,
  GROQ_API_KEY: process.env.GROQ_API_KEY,
  LOST_ITEM_API_URL: process.env.LOST_ITEM_API_URL,
  VAULTIFY_API_URL: process.env.VAULTIFY_API_URL,
  SEAT_FINDER_API_URL: process.env.SEAT_FINDER_API_URL,
  STUDENT_PORTAL_API_URL: process.env.STUDENT_PORTAL_API_URL,
  PRIVACY_URL: process.env.PRIVACY_URL,
  MONGODB_URI: process.env.MONGODB_URI,
  TASK_SERVICE_URL: process.env.TASK_SERVICE_URL,
};
