module.exports = {
  TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
  API_BASE_URL: process.env.API_BASE_URL,
  WEBHOOK_URL:process.env.WEBHOOK_URL,
  PORT:process.env.PORT,
  NOTIFICATION_API_URL: process.env.NOTIFICATION_API_URL,
  LOST_ITEM_API_URL: process.env.LOST_ITEM_API_URL,
  VAULTIFY_API_URL: process.env.VAULTIFY_API_URL,
  SEAT_FINDER_API_URL: process.env.SEAT_FINDER_API_URL,
  STUDENT_PORTAL_API_URL: process.env.STUDENT_PORTAL_API_URL,
  PRIVACY_URL: process.env.PRIVACY_URL,
  MONGODB_URI: process.env.MONGODB_URI,
  TASK_SERVICE_URL: process.env.TASK_SERVICE_URL,

};
